### ISSUE TITLE
`q=` query with `or` does not work as expected

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#520] opened 2024-08-02 17:18 UTC
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

I tried to query my local pds registry with:

```
GET /products?q=((pds:Target_Identification.pds:name eq "Moon") or (cart:Geodetic_Model.cart:spheroid_name eq "MOON"))&limit=10000
```

And expected to see all labels with Moon target name or MOON spheroid name. However, I instead got no data at all. Each of these alone produced what I expected, ~1000 for target name and ~285 for spheroid name.

After adding the target name tags to the lola xml, I got back only the lola xml. So it seems like or is functioning as and.

### 🕵️ Expected behavior

I expected to get back around 1283 responses.

### 📜 To Reproduce

1. Create treks and lola pds4 xml from the commands in the registry. Lola command is not merged, but on branch stac_utility

2. load the xml files into the registry

3. go to or curl `http://localhost:8080/products?q=((pds:Target_Identification.pds:name eq "Moon") or (cart:Geodetic_Model.cart:spheroid_name eq "MOON"))&limit=10000`

### 🖥 Environment Info

Version of this software stac_utility branch of registry
Operating System: Intel Macbook

### 🦄 Related requirements
TBD

**Comment by mattanikiej** [comment] 2024-08-02 17:39
Checked for duplicates

No - I haven't checked

🐛 Describe the bug

I tried to query my local pds registry with:

`http://localhost:8080/products?q=((pds:Target_Identification.pds:name eq "Moon") or (cart:Geodetic_Model.cart:spheroid_name eq "MOON"))&limit=10000`

And expected to see all labels with Moon target name or MOON spheroid name. However, I instead got no data at all. Each of these alone produced what I expected, ~1000 for target name and ~285 for spheroid name.

After adding the target name tags to the lola xml, I got back only the lola xml. So it seems like `or` is functioning as `and`.

🕵️ Expected behavior

I expected to get back around 1283 responses.

📜 To Reproduce
1. Create treks and lola pds4 xml from the commands in the registry. Lola command is not merged, but on branch stac_utility
2. load the xml files into the registry
3. go to `http://localhost:8080/products?q=((pds:Target_Identification.pds:name eq "Moon") or (cart:Geodetic_Model.cart:spheroid_name eq "MOON"))&limit=10000`
...
🖥 Environment Info

    Version of this software stac_utility branch of registry
    Operating System: Intel Macbook
    ...

📚 Version of Software Used

No response
🩺 Test Data / Additional context

No response
🦄 Related requirements

🦄 #xyz
⚙️ Engineering Details

No response
🎉 Integration & Test

No response

**Comment by alexdunnjpl** [comment] 2024-09-06 00:48
@tloubrieu-jpl do you still have this environment set up?  I was hoping you might be able to test with an up-to-date version of registry-api before I dive into trying to replicate - the following initial tests against the I&T database init indicate that `OR`/`or` is working as intended.

With two bundles, four collections:

`http://localhost:8081/products?q=((product_class EQ "Product_Collection") or (product_class EQ "Product_Bundle"))` returns 6

`http://localhost:8081/products?q=((product_class EQ "Product_Collection") and (product_class EQ "Product_Bundle"))` returns 0

**Comment by alexdunnjpl** [comment] 2024-09-11 17:49
Confirmed working as-expected on production API, too:

534 Bundle
1992 Collection
1992 Collection or Collection
1992 Collection OR Collection
2526 Bundle Or Collection

**Comment by alexdunnjpl** [comment] 2024-09-11 17:58
Running original query against prod registry/API

A - `https://pds.mcp.nasa.gov/api/search/1/products?q=(pds:Target_Identification.pds:name eq "Moon")` returns 2822398
B -`https://pds.mcp.nasa.gov/api/search/1/products?q=(cart:Geodetic_Model.cart:spheroid_name eq "MOON")` returns 288

A or B returns 2822398
A and B returns 288

So behaviour is as-expected

**Comment by alexdunnjpl** [comment] 2024-09-11 18:30
Closing as not-a-bug after confirming with @tloubrieu-jpl

**Closed as completed by alexdunnjpl** 2024-09-11 18:30 UTC
Labels: B15.0, bug, invalid, s.high, sprint-backlog, wontfix, i&t.skip, open.1.5.0

**Comment by c-suh** [comment] 2024-11-12 22:07
Because this wasn't reproduced, it is not a bug and should be "skip i&t"
