### ISSUE TITLE
As a user, by default, I want to resolve the latest version of a product when given a product logical_identifier (LID) (`/products/{logical_identifier}` endpoint)

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#503] opened 2024-07-19 12:40 UTC
### Checked for duplicates

No - I haven't checked

### 💪 Motivation

...so that I can [why do you want to do this?]

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment] 2024-07-19 13:50
Closed as duplicate of https://github.com/NASA-PDS/registry-api/issues/435

**Closed as completed by tloubrieu-jpl** 2024-07-19 13:50 UTC
Labels: B15.0, duplicate, p.must-have, requirement
