### ISSUE TITLE
As an user, I want only specific fields to be returned when I query the API (`fields=`)

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/registry-api#80] opened 2022-01-19 22:10 UTC
```
$ curl --location --request GET 'http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0?fields=lid,lidvid' --header 'Accept: application/kvp+json'
{
  "summary":{"hits":1,"took":9,"start":0,"limit":10,"sort":[],"properties":["*"]},
  "data":[    {
      "ops:Label_File_Info.ops:md5_checksum":"a8d09cca0a01728db50c15052c2736cf",
      "ops:Data_File_Info.ops:creation_date_time":"2021-05-12T18:17:17Z",
      "ref_lid_instrument_host":"urn:nasa:pds:context:instrument_host:spacecraft.mess",
      "ops:Label_File_Info.ops:creation_date_time":"2021-05-12T18:17:17Z",
      "lid":"urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst",
      "ops:Data_File_Info.ops:mime_type":"application/pdf",
      "ref_lid_investigation":"urn:nasa:pds:context:investigation:mission.messenger",
      "lidvid":"urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0",
      "title":"MESSENGER Neutron Spectrometer (NS) Description",
      "ops:Data_File_Info.ops:file_ref":"/var/local/harvest/archive/document/ns_inst.pdf",
      "_package_id":"39728247-ff50-467c-92a2-65827eb27eec",
      "ref_lid_instrument":"urn:nasa:pds:context:instrument:ns.mess",
      "ops:Harvest_Info.ops:node_name":"PSA",
      "ops:Label_File_Info.ops:file_size":"3589",
      "vid":"1.0",
      "product_class":"Product_Document",
      "ops:Data_File_Info.ops:file_name":"ns_inst.pdf",
      "ops:Data_File_Info.ops:md5_checksum":"8103f20c13a3c321dac4a193aba19d16",
      "ops:Label_File_Info.ops:file_name":"ns_inst.xml",
      "ref_lid_target":"urn:nasa:pds:context:target:planet.mercury",
      "ops:Label_File_Info.ops:file_ref":"/var/local/harvest/archive/document/ns_inst.xml",
      "ops:Data_File_Info.ops:file_size":"138172"    }
  ]
}
```
## 💪 Motivation

The desire was to get just the lid and lidvid (yeah, dumb example) but have to sift through stuff not desired. Could say the same thing about `ops:Label_File_Info.ops:md5_checksum` for a more meaningful example but requires too much typing on the command line.

Note: the definition of the [endpoint](https://github.com/NASA-PDS/registry-api/blob/a72b40eee36a6cea953a2a9e7ed3ffc0b4c0b649/service/src/main/java/gov/nasa/pds/api/engineering/controllers/MyProductsApiController.java#L59) seems to exclude the fields.

## ⚖️ Acceptance Criteria
```
$ curl --location --request GET 'http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0?fields=lid,lidvid' --header 'Accept: application/kvp+json'
{
  "summary":{"hits":1,"took":9,"start":0,"limit":10,"sort":[],"properties":["*"]},
  "data":[    {
     "lid":"urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst",
      "lidvid":"urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0",
  ]
}
```

**Comment by tloubrieu-jpl** [comment] 2022-01-20 17:54
closed by mistake

**Comment by tloubrieu-jpl** [comment] 2022-04-19 17:28
That works well, seen in PR #112

**Closed as completed** 2022-04-19 20:07 UTC
Labels: B12.1, duplicate, p.could-have, requirement

**Comment by jordanpadams** [comment] 2024-09-26 16:55
duplicate of #459
