### ISSUE TITLE
Add Provenance CW Alarm components to terraform script

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#290] opened 2023-03-16 19:04 UTC
Placeholder ticket to make sure it gets done.

For exploration, the CW Alarm components for the provenance script execution were manually created. Their needs to be captured in a terraform script - likely added to that which creates the scheduled provenance execution.

Related issues:
https://github.com/NASA-PDS/registry-api/issues/265
https://github.com/NASA-PDS/operations/issues/367

**Comment by tloubrieu-jpl** [comment] 2023-05-03 16:31
This ticket is a duplicate of https://github.com/NASA-PDS/registry-sweepers/issues/9

**Closed as completed by tloubrieu-jpl** 2023-05-03 16:31 UTC
Labels: B14.0, duplicate, task, i&t.skip
