### ISSUE TITLE
API silently ignores bad/unsupported query parameters in requests

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#237] opened 2023-01-19 23:18 UTC
## 🐛 Describe the bug
API silently ignores bad/unsupported query parameters in requests.  This can confuse users as the API will respond with an unfiltered list of all resources the user is attempting to filter on.

## 📜 To Reproduce
1. Curl or browse `https://pds.nasa.gov/api/search/1/classes/collections?identifier=urn%3Anasa%3Apds%3Ainsight_rad%3Adata_derived%3A%3A7.0`
2. Observe that response returns query equivalent to https://pds.nasa.gov/api/search/1/classes/collections with a blank query string `q=""`

## 🕵️ Expected behavior
Presence of unexpected query parameters should (maybe) return HTTP400 bad request 

## 🖥 System Info

---

**Comment by tloubrieu-jpl** [comment] 2023-01-24 00:25
duplicate of https://github.com/NASA-PDS/pds-api/issues/252

**Closed as completed** 2023-02-09 00:40 UTC
Labels: bug, duplicate
